<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>bebeb886-c1d8-4591-8109-3237fe5c83f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/span/span/button/span/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f67e6d33-db60-4b53-9b2e-50580eaa7a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>e2951df6-6735-4260-b355-8b69f5cd6341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7038_1663761128559.name</value>
      <webElementGuid>f3ac6eaf-0006-4a8b-921c-fc9baf4b4bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7038_1663761128559.name</value>
      <webElementGuid>c3059a5b-b378-48ef-a42a-ecc0d19fef23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lazy</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>5d546ebb-99a9-4308-bf30-99f0da0fbdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;app-wrapper openSidebar&quot;]/div[@class=&quot;side-menu&quot;]/div[@class=&quot;user-info el-row&quot;]/span[1]/span[@class=&quot;el-popover__reference-wrapper&quot;]/button[@class=&quot;el-button is-create-color is-white is-none-border icon-btn p-0 m-0 el-button--default el-popover__reference&quot;]/span[1]/div[@class=&quot;custom-avatar div-place-img div-img-ssm round&quot;]/img[1]</value>
      <webElementGuid>c8821150-cfd9-45eb-ba65-1411b9690c2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/span/span/button/span/div/img</value>
      <webElementGuid>53b36d96-eb24-495a-990b-e25c38ad246a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>31fa202a-12cf-47f3-89af-9c96a63eeb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>feff07fd-1754-4154-86ba-29c89aab990b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'logo' and @src = 'https://s3.cloud.cmctelecom.vn/bework-production/user/avatar/7038_1663761128559.name']</value>
      <webElementGuid>ff4afe6d-a7ab-4e7f-8534-c7f6c4c47c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
